name: Deploy Tunnel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start Cloudflared Tunnel
        run: |
          echo "${{ secrets.CLOUDFLARED_JSON }}" > tunnel.json
          npx cloudflared tunnel --cred-file tunnel.json run n8n-Tunnel
